-- Run this in Supabase Dashboard -> SQL Editor.
-- This table stores applications and the date selected by each applicant.

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  height_cm numeric(5,1) not null check (height_cm between 50 and 250),
  weight_kg numeric(5,1) not null check (weight_kg between 20 and 250),
  hobbies text not null check (char_length(hobbies) between 1 and 500),
  date_day date not null,
  created_at timestamptz not null default now()
);

alter table public.applications enable row level security;

-- Public website: visitors can submit an application.
drop policy if exists "Anyone can submit applications" on public.applications;
create policy "Anyone can submit applications"
on public.applications
for insert
to anon
with check (true);

-- Public website: visitors can see the scoreboard.
-- Only non-sensitive display fields should be selected by the website.
drop policy if exists "Anyone can view applications" on public.applications;
create policy "Anyone can view applications"
on public.applications
for select
to anon
using (true);
